config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  root 'tasks#index'
  post '/tasks/:id/toggle' => 'tasks#toggle'
  get 'tasks/show'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title,
  presence: { message: 'タイトルを入力して下さい！'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task =Task.new(task_params)

    if @task.save
      redirect_to root_path
    else
      render 'new'
     end
  end

  def edit
    @task =Task.find(params[:id])
  end

  def update
    @task =Task.find(params[:id])
    
    if @task.update(task_params)
      redirect_to root_path
    else
      render'edit'
    end
  end

  def destroy
    @task =Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  def toggle
    head :no_content
    @task =Task.find(params[:id])
    @task.done= !@task.done
    @task.save
  end

  def show
  end

  private
    def task_params
      params[:task].permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Trello Clone</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
    <% #if signed_in? %>
      <li id='add-dropdown' class='dropdown'>
        <button 
          class='dropdown-toggle navbar-btn btn btn-primary'
          data-toggle='dropdown'><span class='glyphicon glyphicon-plus'></span>
        </button>
      </li>
      <li><%= button_to "Sign out", session_url, method: :delete, class: "btn btn-primary navbar-btn" %></li>
    <% else %>
      <li><%= link_to "Log in", new_session_url %></li>
      <li><%= link_to "Sign up", new_user_url %></li>
    <% end %>
    </ul>
  </div>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
  </head>

  <body>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
     <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>編集画面</h1>
<%= form_for @task do |f| %>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    <% if @task.errors.any? %>
      <%= @task.errors.messages[:title][0] %>
    <% end %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tasks/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>ToDoアプリ</title>
    <link rel="stylesheet" href="stylesheet.css">
  </head>
  <body>
    <div class="header">
      <div class="header-logo">ToDoアプリ</div>
      <div class="header-list">
        <ul>
          <li>ログアウト</li>
          <li><%= link_to 'リストの作成', new_task_path %></li>
          <li>kitagawa</li>
        </ul>
      </div>
    </div>

    <div class="main">
    <ul>
      <% @tasks.each do |task| %>
        <li>
          <%= check_box_tag '','', task.done, {'data-id' => task.id} %>
          <%= task.title %>
          <%= link_to '[編集]',edit_task_path(task.id)%>
          <%= link_to '[削除]',
            task_path(task.id), 
            method: :delete, 
            data:{ confirm: '削除してもよろしいですか？'} %>
        </li>
      <% end %>
    </ul>

    
    <!--<%= link_to 'ページ一覧', tasks_show_path %> -->

    <script>
      $(function(){
        $("input[type=checkbox]").click(function(){
          $.post('/tasks/' + $(this).data('id') + '/toggle');
        }); 
      });
    </script>
    

    <div class="contact-form">
        <h3 class="section-title">お問い合わせ</h3>
        <p>メールアドレス（必須）</p>
        <!-- <input>要素を追加してください -->
        <input>
        
        <p>お問い合わせ内容（必須）</p>
        <!-- <textarea>要素を追加してください -->
        <textarea></textarea>
        
        <p>※必須項目は必ずご入力ください</p>
        <!-- <input>要素を追加してください -->
        <input class="contact-submit" type="submit" value="送信">
        
      </div>
    </div>
    <div class="footer">
      <div class="footer-logo">ToDoアプリ</div>
      <div class="footer-list">
        <ul>
          <li></li>
          <li></li>
          <li></li>
        </ul>
      </div>
    </div>
  </body>
</html>

app/views/tasks/new.html.erb
<h1>新規追加画面</h1>
<%= form_for @task do |f| %>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    <% if @task.errors.any? %>
      <%= @task.errors.messages[:title][0] %>
    <% end %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tasks/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>個人アプリ</title>
    <link rel="stylesheet" href="stylesheet.css">
  </head>
  <body>
    <div class="header">
      <div class="header-logo">個人アプリ</div>
      <div class="header-list">
        <ul>
          <li>プログラミングとは</li>
          <li>学べるレッスン</li>
          <li>お問い合わせ</li>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="copy-container">
        <h1>HELLO WORLD<span>.</span></h1>
        <h2>プログラミングの世界へようこそ</h2>
      </div>
      
      <div class="contents">
        <h3 class="section-title">学べるレッスン</h3>
        <div class="contents-item">
          <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/html.svg">
          <p>HTML & CSS</p>
        </div>
        <div class="contents-item">
          <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/php.svg">
          <p>PHP</p>
        </div>
        <div class="contents-item">
          <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/ruby.svg">
          <p>Ruby</p>
        </div>
        <div class="contents-item">
          <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/swift.svg">
          <p>Swift</p>
        </div>
      </div>
      
      <div class="contact-form">
        <h3 class="section-title">お問い合わせ</h3>
        <p>メールアドレス（必須）</p>
        <!-- <input>要素を追加してください -->
        <input>
        
        <p>お問い合わせ内容（必須）</p>
        <!-- <textarea>要素を追加してください -->
        <textarea></textarea>
        
        <p>※必須項目は必ずご入力ください</p>
        <!-- <input>要素を追加してください -->
        <input class="contact-submit" type="submit" value="送信">
        
      </div>
    </div>

    <div class="footer">
      <div class="footer-logo">個人アプリ</div>
      <div class="footer-list">
        <ul>
          <li>会社概要</li>
          <li>採用</li>
          <li>お問い合わせ</li>
        </ul>
      </div>
    </div>
  </body>
</html>

app/views/tasks/todo.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>個人アプリ</title>
    <link rel="stylesheet" href="stylesheet.css">
  </head>
  <body>
    <div class="header">
      <div class="header-logo">個人アプリ</div>
      <div class="header-list">
        <ul>
          <li>プログラミングとは</li>
          <li>学べるレッスン</li>
          <li>お問い合わせ</li>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="copy-container">
        <h1>HELLO WORLD<span>.</span></h1>
        <h2>プログラミングの世界へようこそ</h2>
      </div>
      
      <div class="contents">
        <h3 class="section-title">学べるレッスン</h3>
        <div class="contents-item">
          <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/html.svg">
          <p>HTML & CSS</p>
        </div>
        <div class="contents-item">
          <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/php.svg">
          <p>PHP</p>
        </div>
        <div class="contents-item">
          <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/ruby.svg">
          <p>Ruby</p>
        </div>
        <div class="contents-item">
          <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/swift.svg">
          <p>Swift</p>
        </div>
      </div>
      
      <div class="contact-form">
        <h3 class="section-title">お問い合わせ</h3>
        <p>メールアドレス（必須）</p>
        <!-- <input>要素を追加してください -->
        <input>
        
        <p>お問い合わせ内容（必須）</p>
        <!-- <textarea>要素を追加してください -->
        <textarea></textarea>
        
        <p>※必須項目は必ずご入力ください</p>
        <!-- <input>要素を追加してください -->
        <input class="contact-submit" type="submit" value="送信">
        
      </div>
    </div>

    <div class="footer">
      <div class="footer-logo">個人アプリ</div>
      <div class="footer-list">
        <ul>
          <li>会社概要</li>
          <li>採用</li>
          <li>お問い合わせ</li>
        </ul>
      </div>
    </div>
  </body>
</html>